config/routes.rb
Rails.application.routes.draw do
  root 'books#index'
  get 'readers/index'
  get 'authors/index'
  get 'books', to: 'books#index'
  get 'subjects', to: 'subjects#index'
  get 'authors', to: 'authors#index'
  get 'about', to: 'about#index'
  get 'subjects/:id/books', to: 'subjects#books', as: 'subject_books'

  resources :books, only: [:index, :show]
  resources :subjects do
    member do
      get 'books'  # Add this line to define the 'books' action as a member route
    end
  end
  resources :authors, only: [:index, :show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord

  has_and_belongs_to_many :books

end

app/models/book.rb
class Book < ApplicationRecord
  
  has_and_belongs_to_many :authors
  has_and_belongs_to_many :subjects
  has_and_belongs_to_many :readers

  validates :title, presence: true
  validates :description, presence: true
  
end

app/models/reader.rb
class Reader < ApplicationRecord
  
  has_and_belongs_to_many :books
  
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_and_belongs_to_many :books
  validates :subject_name, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.paginate(page: params[:page], per_page: 10)
  end

  def show
    @author = Author.find(params[:id])
    @books = @author.books
  end

end

app/controllers/authors_controllers.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.page(params[:page]).per(10)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  def index
    if params[:search].present? && params[:subject].present?
      @books = Book.joins(:subjects).where("books.title LIKE ? AND subjects.id = ?", "%#{params[:search]}%", params[:subject]).paginate(page: params[:page], per_page: 10)
    elsif params[:search].present? && params[:subject].blank?
      @books = Book.where("title LIKE ?", "%#{params[:search]}%").paginate(page: params[:page], per_page: 10)
    elsif params[:subject].present?
      @books = Subject.find(params[:subject]).books.paginate(page: params[:page], per_page: 10)
    else
      @books = Book.paginate(page: params[:page], per_page: 10)
    end

    @subjects = Subject.all

    # Display a message when the search query is blank
    @search_query = params[:search] || ""
    @no_query_message = "Please enter a search query" if @search_query.blank?
  end



  def show
    @book = Book.find(params[:id])
  end

end

app/controllers/readers_controller.rb
class ReadersController < ApplicationController
  
  def index
    @readers = Reader.all
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  
  def index
    @subjects = Subject.paginate(page: params[:page], per_page: 10)
  end
  
  def show
    @subject = Subject.find(params[:id])
    @books = @subject.books
  end

  def books
    @subject = Subject.find(params[:id])
    @books = @subject.books

    respond_to do |format|
      format.html {
        # Render HTML template
      }
      format.json {
        render json: @books
      }
    end
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/readers_helper.rb
module ReadersHelper
end

app/views/about/index.html.erb
  <h1>About Page</h1>

  <h2>Description</h2>
  <p>
  The database is designed to store information about books, authors, subjects, and readers. It integrates data from multiple sources, including an API and a CSV file.
  </p>

  <p>
  Books:
  </p>

  <p>
  Each book has a title, description, language, and download count.
  The book data is fetched from the 'https://gutendex.com/books/' API endpoint.
  Books may have one or more authors and multiple subjects.
  The book descriptions are randomly generated using the Faker gem.
  </p>

  <p>
  Authors:
  </p>

  <p>
  Authors have a name and birth year.
  Author data is fetched from the 'https://gutendex.com/books/' API endpoint.
  Multiple authors can be associated with a book.
  </p>

  <p>
  Subjects:
  </p>

  <p>
  Subjects represent different categories or topics related to books.
  Subject data is fetched from the 'https://gutendex.com/books/' API endpoint.
  Each subject has a unique name.
  Multiple subjects can be associated with a book.
  </p>

  <p>
  Readers:
  </p>

  <p>
  Readers are individuals who read books.
  Each reader has a name and tracks the number of books read, books currently being read, and saved books.
  Reader records are randomly created using the Faker gem.
  Each book can be assigned to one reader.
  </p>

  <p>
  CSV Integration:
  </p>

  <p>
  The 'book.csv' file is read and processed using the CSV library.
  Additional books are created based on the data in the CSV file.
  The CSV file contains information about book titles, authors, subjects, downloads, languages, and author birth years.
  Books from the CSV file are associated with authors and subjects as per the existing associations in the database.
  </p>

  <p>
  the sources for the database include:
  </p>

  <p>
  Gutendex API:
  </p>

  <p>
  'https://gutendex.com/books/' endpoint for fetching book data.
  'https://gutendex.com/books/' endpoint for fetching subject data.
  'https://gutendex.com/books/' endpoint for fetching author data.
  </p>

  <p>
  CSV File:
  </p>

  <p>
  'book.csv' file containing additional book data.
  </p>

  <p>
  Faker Gem:
  </p>

  <p>
  Used to generate random data for book descriptions and reader names.
  These sources collectively provide a diverse range of book information and reader data, ensuring a rich and varied database content.
  </p>

  <h2>ERD</h2>
  <img src="<%= asset_path('intro_to_rails.jpg') %>" alt="Intro to Rails ERD">

app/views/authors/index.html.erb
<h1>Authors</h1>

<ul>
  <% @authors.each do |author| %>
    <li>
      <span><%= link_to author.author_name, author_path(author) %></span>
      - Number of Books: <%= author.books.count %>
    </li>
  <% end %>
</ul>

<%= will_paginate @books %>

app/views/authors/show.html.erb
<h1>Author Details</h1>

<strong>Name:</strong> <%= @author.author_name %> <br>

<h2>Books</h2>
<ul>
  <% @books.each do |book| %>

    <li>
      <strong>Title:</strong> <%= link_to book.title, book_path(book) %> <br>
      <strong>Description:</strong> <%= book.description %> <br>
      <strong>Language:</strong> <%= book.language %> <br>
    </li>

  <% end %>

</ul>

app/views/books/index.html.erb
<%= form_with(url: books_path, method: "get") do |f| %>
  <%= f.text_field :search, value: @search_query, placeholder: "Search books..." %>
  <%= f.select :subject, options_for_select(@subjects.map { |s| [s.subject_name, s.id] }, params[:subject]), prompt: "Select a subject" %>
  <%= f.submit "Search" %>
<% end %>

<% if @no_query_message %>
  <p><%= @no_query_message %></p>
<% end %>

<ul>
  <% @books.each do |book| %>
    <li>
      <strong>Title:</strong> <%= link_to book.title, book_path(book) %> <br>
      <strong>Description:</strong> <%= book.description %> <br>
      <strong>Language:</strong> <%= book.language %> <br>
    </li>
  <% end %>
</ul>

<%= will_paginate @books %>

app/views/books/show.html.erb
<h1><%= @book.title %></h1>
<p><strong>Authors:</strong> <%= @book.authors.pluck(:author_name).join(', ') %></p>
<p><strong>Subjects:</strong>
  <% @book.subjects.each do |subject| %>
    <%= link_to subject.subject_name, subject_path(subject) %>
    <%= ', ' unless subject == @book.subjects.last %>
  <% end %>
</p>
<p><strong>Description:</strong> <%= @book.description %></p>
<p><strong>Readers:</strong> <%= @book.readers.count %></p>
<p><strong>Downloads:</strong> <%= @book.downloads %></p>

<h2>Reader Information</h2>
<p><strong>Readers Currently Reading:</strong> <%= @book.readers.where(books_reading: @book.id).count %></p>
<p><strong>Readers Saved to Read Later:</strong> <%= @book.readers.where(books_saved: @book.id).count %></p>
<p><strong>Readers Already Read:</strong> <%= @book.readers.where(books_read: @book.id).count %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Your Application</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
</head>
<body>
  <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to 'Books', books_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Subjects', subjects_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Authors', authors_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'About', about_path, class: 'nav-link' %>
          </li>
        </ul>
      </div>
    </nav>

    <div class="row">
      <div class="col-md-9">
        <%= yield %>
      </div>
      <div class="col-md-3">
        <!-- Sidebar content goes here -->
      </div>
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

app/views/subjects/books.html.erb
<h1>Books</h1>

<% if @books.present? %>
  <ul>
    <% @books.each do |book| %>
      <li>
      <strong>Title:</strong><%= link_to book.title, book_path(book) %>  <br>
      <strong>Description:</strong> <%= book.description %><br>
      <strong>Language:</strong> <%= book.language %><br>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>No books found.</p>
<% end %>

app/views/subjects/index.html.erb
<h1>Subjects</h1>

<ul>
  <% @subjects.each do |subject| %>
    <li>
      <a href="<%= subject_books_path(subject) %>">
        <%= subject.subject_name %>
      </a>
      Count: <%= subject.books.count %>
    </li>
  <% end %>
</ul>
<%= will_paginate @books %>

app/views/subjects/show.html.erb
<h1><%= @subject.subject_name %></h1>

<p>Count of Associated Books: <%= @books.count %></p>

<h2>Associated Books</h2>

<% if @books.present? %>
  <ul>
    <% @books.each do |book| %>
      <li>
      <strong>Title:</strong> <%= link_to book.title, book_path(book) %> <br>
      <strong>Description:</strong> <%= book.description %> <br>
      <strong>Language:</strong> <%= book.language %> <br>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>No books associated with this subject.</p>
<% end %>